apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: goods-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: kdk-fun-secret
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: goods-nginx
          servicePort: 80