apiVersion: v1
kind: Service
metadata:
  labels:
    run: goods-nginx
  name: goods-nginx
spec:
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: goods-nginx
  type: NodePort
