apiVersion: v1
kind: Service
metadata:
  labels:
    run: goods
  name: goods
spec:
  ports:
  - name: server
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: goods
  type: ClusterIP
